---

services:
  web:
    container_name: frontend
    hostname: frontend
    image: ghcr.io/tonyskidmore/chatgpt-create-react-app/frontend:latest
    ports:
      - "3000:80"
    environment:
    - REACT_APP_API_URL=http://localhost:8000
    build:
      context: frontend/
      dockerfile: Dockerfile
  api:
    container_name: backend
    hostname: backend
    image: ghcr.io/tonyskidmore/chatgpt-create-react-app/backend:latest
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
    build:
      context: backend/
      dockerfile: Dockerfile
  redis:
    container_name: redis
    hostname: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379:0,local:redis:6379:1
    ports:
    - "8081:8081"

volumes:
  redis_data:
